// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_language_path_ from './routes/[language]/[...path].tsx';
import * as $_404 from './routes/_404.tsx';
import * as $_500 from './routes/_500.tsx';
import * as $_app from './routes/_app.tsx';
import * as $_middleware from './routes/_middleware.ts';
import * as $api_language_paragraph_paragraph_number_range_ from './routes/api/[language]/paragraph/[paragraph_number_range].ts';
import * as $index from './routes/index.tsx';
import * as $select_language from './routes/select-language.tsx';
import * as $ui_demo from './routes/ui-demo.tsx';
import * as $_islands_auto_scroller from './routes/(_islands)/auto-scroller.tsx';
import * as $_islands_changelog_trigger from './routes/(_islands)/changelog-trigger.tsx';
import * as $_islands_changelog from './routes/(_islands)/changelog.tsx';
import * as $_islands_cross_reference_link from './routes/(_islands)/cross-reference-link.tsx';
import * as $_islands_cross_reference_window from './routes/(_islands)/cross-reference-window.tsx';
import * as $_islands_dark_mode_toggle from './routes/(_islands)/dark-mode-toggle.tsx';
import * as $_islands_reference_links from './routes/(_islands)/reference-links.tsx';
import * as $_islands_ui_library_demo_menu from './routes/(_islands)/ui-library-demo/menu.tsx';
import * as $_islands_ui_library_demo_popover from './routes/(_islands)/ui-library-demo/popover.tsx';
import * as $_islands_ui_library_demo_template from './routes/(_islands)/ui-library-demo/template.tsx';
import { type Manifest } from '$fresh/server.ts';

const manifest = {
    routes: {
        './routes/[language]/[...path].tsx': $_language_path_,
        './routes/_404.tsx': $_404,
        './routes/_500.tsx': $_500,
        './routes/_app.tsx': $_app,
        './routes/_middleware.ts': $_middleware,
        './routes/api/[language]/paragraph/[paragraph_number_range].ts':
            $api_language_paragraph_paragraph_number_range_,
        './routes/index.tsx': $index,
        './routes/select-language.tsx': $select_language,
        './routes/ui-demo.tsx': $ui_demo,
    },
    islands: {
        './routes/(_islands)/auto-scroller.tsx': $_islands_auto_scroller,
        './routes/(_islands)/changelog-trigger.tsx': $_islands_changelog_trigger,
        './routes/(_islands)/changelog.tsx': $_islands_changelog,
        './routes/(_islands)/cross-reference-link.tsx': $_islands_cross_reference_link,
        './routes/(_islands)/cross-reference-window.tsx': $_islands_cross_reference_window,
        './routes/(_islands)/dark-mode-toggle.tsx': $_islands_dark_mode_toggle,
        './routes/(_islands)/reference-links.tsx': $_islands_reference_links,
        './routes/(_islands)/ui-library-demo/menu.tsx': $_islands_ui_library_demo_menu,
        './routes/(_islands)/ui-library-demo/popover.tsx': $_islands_ui_library_demo_popover,
        './routes/(_islands)/ui-library-demo/template.tsx': $_islands_ui_library_demo_template,
    },
    baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
