name: Deploy
on:
  push:
    branches:
      - master
      - staging
      - dev
  pull_request:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install step
        run: "cd website && deno install --frozen --allow-scripts=npm:sharp"

      - name: Disable Astro telemetry
        run: "cd website && deno task disable-telemetry"

      - name: Build step
        run: "cd website && deno task build-on-deployment-platform"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "catholic-catechism"
          entrypoint: "server/entry.mjs"
          root: "website/dist"
